name: rctGCS
channels:
  - defaults
  - anaconda
  - conda-forge

dependencies:
  - qgis=3.10.2
  - gdal=3.0.2
  - python=3.6
  - pip=20.0.2
  - scipy=1.4.1
  - basemap=1.3.0
  - basemap-data-hires=1.2.0
  - pillow=7.1.2
  - pip:
    - utm==0.5.0
    - PyQt5==5.15.0
    - xlwt

