name: rctGCS
channels:
  - defaults
  - anaconda
  - conda-forge

dependencies:
  - qgis
  - python=3.9
  - pip=20.0.2
  - scipy
  - pip:
    - utm==0.5.0
    - xlwt
<<<<<<< HEAD
    - appdirs
=======
    - appdirs==1.4.4
>>>>>>> v1.a_ML1

