name: rctGCS
channels:
  - defaults
  - anaconda
  - conda-forge

dependencies:
  - qgis
  - python=3.9
  - pip=20.0.2
  - scipy
  - pip:
    - utm==0.5.0
    - xlwt
    - appdirs==1.4.4
    - ipython
    - git+https://github.com/UCSD-E4E/radio_collar_tracker_comms.git
