name: rctGCS
channels:
  - defaults
  - anaconda
  - conda-forge

dependencies:
  - qgis=3.18.3
  - python=3.9
  - pip
  - scipy
  - pip:
    - utm
    - xlwt
    - appdirs
    - ipython
    # - RCTComms @ git+https://github.com/UCSD-E4E/radio_collar_tracker_comms.git@v0.0.0.9
