name: osx pytest

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniconda-version: "latest"
          environment-file: conda-osx-64-lock.yml
    - name: Install dependencies
      run: |
        poetry install
    - name: Execute tests
      run: |
        python -m pytest tests
