name: ubuntu pytest

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: false
        activate-environment: rctGCS
        environment-file: conda-linux-64-lock.yml
    - name: Install dependencies
      run: |
        conda activate rctGCS
        python -m poetry install
    - name: Execute tests
      run: |
        conda activate rctGCS
        conda list
        conda info
        conda info --envs
        printenv
        python -m pytest tests
