name: windows pytest

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: latest
        auto-update-conda: false
        activate-environment: rctGCS
        environment-file: conda-win-64-lock.yml
    - name: Install dependencies
      shell: powershell
      run: |
        conda activate rctGCS
        python -m poetry install
    - name: Execute tests
      shell: powershell
      run: |
        conda activate rctGCS
        python -m pytest tests